#! /usr/bin/env bash

SERVER_DIR='../server/public'

function copyNew () {
	npm run build
    cp -r build/* ${SERVER_DIR}/.
}

function deleteOld () {
	rm -v ${SERVER_DIR}/precache-manifest*.js
	rm -v ${SERVER_DIR}/service-worker.js
	rm -v -r ${SERVER_DIR}'/static'
}

deleteOld
copyNew
