#! /bin/bash

LOCAL_IP=$(~/bin/./get-ip.js)

RED='\033[0;31m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color
BLUE='\033[1;36m'

function show {
    sudo systemctl show -p ActiveState -p SubState -p Environment $2
}

function showSystemCheck() {
    show 'SystemCheck' systemcheck.service
}

function showSystemCheckRefactor() {
    show 'SystemCheckRefactor' scref.service
}

function showAwsProvision() {
    show 'AwsProvision' aws.service
}

function showMidterm() {
    show 'Midterm' midterm.service
}

function showEC2CopyFile() {
    show 'EC2CopyFile' copyFile.service
}

function checkPorts() {
    sudo nmap -p 30025-30035 ${LOCAL_IP}
}

echo ' '     # new line
echo ===============================
echo 'System Service Control'
echo 'Learn about Systemd and other running services.'
echo ===============================

while true; do
	echo " "   # new line
    echo -e "$BLUE Menu"    
    echo -e "$LIGHT_GREEN  a) Check Ports 30025-30040"
    echo -e "$LIGHT_GREEN  b) SystemCheck"
    echo -e "$LIGHT_GREEN  c) SystemCheckRefactor"
    echo -e "$LIGHT_GREEN  d) AWS Provision"
    echo -e "$LIGHT_GREEN  e) Midterm"
    echo -e "$LIGHT_GREEN  f) EC2-Copy-File"
    echo -e "$LIGHT_RED  x) Exit"
    echo -e "\n$NC"
    read -p "Please make a selection: " userInput
    case $userInput in
        [Aa]* ) checkPorts false; continue;;
        [Bb]* ) showSystemCheck; continue;;
        [Cc]* ) showSystemCheckRefactor; continue;;
        [Dd]* ) showAwsProvision; continue;;
        [Ee]* ) showMidterm; continue;;
        [Ff]* ) showEC2CopyFile; continue;;
        [XxQq]* ) break;;
        *) echo -e "\n$NC" + "Please answer with a through f or x.";;
    esac
done
