#! /bin/bash

function copyService() {
    sudo cp -v ec2-copy-file.service /etc/systemd/system/.
    sudo systemctl enable ec2-copy-file.service
    sudo systemctl start ec2-copy-file.service
}

copyService
